// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATH1AX_O_SupimE4wHXUWi0OSvJrGltqI',
    appId: '1:557968617347:web:2cb98e5ffa9a90c50890b6',
    messagingSenderId: '557968617347',
    projectId: 'latuni-e3187',
    authDomain: 'latuni-e3187.firebaseapp.com',
    storageBucket: 'latuni-e3187.appspot.com',
    measurementId: 'G-4J5PLBV3GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwlM8Gf9zvMwnBTX1lo9BYntAT2apcYE',
    appId: '1:557968617347:android:5fb6e8975a6c24ae0890b6',
    messagingSenderId: '557968617347',
    projectId: 'latuni-e3187',
    storageBucket: 'latuni-e3187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu3DV29sjSh7RA89hXGkMX0XcjPuKpSOo',
    appId: '1:557968617347:ios:06c4adee4b378bcc0890b6',
    messagingSenderId: '557968617347',
    projectId: 'latuni-e3187',
    storageBucket: 'latuni-e3187.appspot.com',
    iosBundleId: 'com.example.latuni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu3DV29sjSh7RA89hXGkMX0XcjPuKpSOo',
    appId: '1:557968617347:ios:9d95dec55b37c0940890b6',
    messagingSenderId: '557968617347',
    projectId: 'latuni-e3187',
    storageBucket: 'latuni-e3187.appspot.com',
    iosBundleId: 'com.example.latuni.RunnerTests',
  );
}
